// <auto-generated />
using CopaHAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopaHAS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260406005502_MigracaoEstadios")]
    partial class MigracaoEstadios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CopaHAS.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capacidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTADIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 82500m,
                            Cidade = "East Rutherford (NY/NJ)",
                            Nome = "MetLife Stadium"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 70240m,
                            Cidade = "Los Angeles (CA)",
                            Nome = "SoFi Stadium"
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = 80000m,
                            Cidade = "Arlington (TX)",
                            Nome = "AT&T Stadium"
                        },
                        new
                        {
                            Id = 4,
                            Capacidade = 71000m,
                            Cidade = "Atlanta (GA)",
                            Nome = "Mercedes-Benz Stadium"
                        },
                        new
                        {
                            Id = 5,
                            Capacidade = 72220m,
                            Cidade = "Houston (TX)",
                            Nome = "NRG Stadium"
                        },
                        new
                        {
                            Id = 6,
                            Capacidade = 68500m,
                            Cidade = "Santa Clara (CA)",
                            Nome = "Levi's Stadium"
                        },
                        new
                        {
                            Id = 7,
                            Capacidade = 68740m,
                            Cidade = "Seattle (WA)",
                            Nome = "Lumen Field"
                        },
                        new
                        {
                            Id = 8,
                            Capacidade = 69596m,
                            Cidade = "Philadelphia (PA)",
                            Nome = "Lincoln Financial Field"
                        },
                        new
                        {
                            Id = 9,
                            Capacidade = 65326m,
                            Cidade = "Miami (FL)",
                            Nome = "Hard Rock Stadium"
                        },
                        new
                        {
                            Id = 10,
                            Capacidade = 76416m,
                            Cidade = "Kansas City (MO)",
                            Nome = "GEHA Field at Arrowhead Stadium"
                        },
                        new
                        {
                            Id = 11,
                            Capacidade = 65878m,
                            Cidade = "Foxborough (MA)",
                            Nome = "Gillette Stadium"
                        },
                        new
                        {
                            Id = 12,
                            Capacidade = 54500m,
                            Cidade = "Vancouver",
                            Nome = "BC Place"
                        },
                        new
                        {
                            Id = 13,
                            Capacidade = 30000m,
                            Cidade = "Toronto",
                            Nome = "BMO Field"
                        },
                        new
                        {
                            Id = 14,
                            Capacidade = 87000m,
                            Cidade = "Cidade do México",
                            Nome = "Estadio Azteca"
                        },
                        new
                        {
                            Id = 15,
                            Capacidade = 53500m,
                            Cidade = "Monterrey",
                            Nome = "Estadio BBVA"
                        },
                        new
                        {
                            Id = 16,
                            Capacidade = 49850m,
                            Cidade = "Guadalajara",
                            Nome = "Estadio Akron"
                        });
                });

            modelBuilder.Entity("CopaHAS.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("int");

                    b.Property<string>("Posicao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_JOGADORES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hugo Souza",
                            NumeroCamisa = 1,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Yuri Alberto",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Danilo",
                            NumeroCamisa = 2,
                            Posicao = "Lateral Direito",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Marquinhos",
                            NumeroCamisa = 4,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Casemiro",
                            NumeroCamisa = 5,
                            Posicao = "Volante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Alex Sandro",
                            NumeroCamisa = 6,
                            Posicao = "Lateral Esquerdo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Lucas Paquetá",
                            NumeroCamisa = 7,
                            Posicao = "Meio Campo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Bruno Guimarães",
                            NumeroCamisa = 8,
                            Posicao = "Meio Campo",
                            SelecaoId = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Richarlison",
                            NumeroCamisa = 10,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Vinicius Jr",
                            NumeroCamisa = 11,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Rodrygo",
                            NumeroCamisa = 19,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Alisson",
                            NumeroCamisa = 23,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
